### PR TITLE
fix pthread_create in uart_new

### PR DESCRIPTION
**Pull request by dzwduan**

### CODE REVIEW

**Comment by ksco** [comment]
Thanks for the PR, but I'm curious what your OS is, it works fine on my computer (macOS 12.3 Intel). Also why remove the -Werror option?

**Comment by dzwduan** [comment]
Linux ubuntu 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dzwduan** [comment]
if not removed, we will get another problems:  src/uart.c: In function ‘uart_thread’:
src/uart.c:8:9: error: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Werror=unused-result]
    8 |         read(STDIN_FILENO, &c, 1);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

and 

src/cpu.c: In function ‘cpu_dump_csrs’:
src/cpu.c:148:29: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
  148 |     printf("mstatus=0x%016llx mtvec=0x%016llx mepc=0x%016llx mcause=0x%016llx\n",
      |                       ~~~~~~^
      |                             |
      |                             long long unsigned int
      |                       %016lx
  149 |         cpu_load_csr(cpu, MSTATUS),
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         |
      |         uint64_t {aka long unsigned int}
src/cpu.c:148:45: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
  148 |     printf("mstatus=0x%016llx mtvec=0x%016llx mepc=0x%016llx mcause=0x%016llx\n",
      |                                       ~~~~~~^
      |                                             |
      |                                             long long unsigned int
      |                                       %016lx
  149 |         cpu_load_csr(cpu, MSTATUS),
  150 |         cpu_load_csr(cpu, MTVEC),
      |         ~~~~~~~~~~~~~~~~~~~~~~~~             
      |         |
      |         uint64_t {aka long unsigned int}
src/cpu.c:148:60: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
  148 |     printf("mstatus=0x%016llx mtvec=0x%016llx mepc=0x%016llx mcause=0x%016llx\n",
      |                                                      ~~~~~~^
      |                                                            |
      |                                                            long long unsigned int
      |                                                      %016lx
......
  151 |         cpu_load_csr(cpu, MEPC),
      |         ~~~~~~~~~~~~~~~~~~~~~~~                             
      |         |
      |         uint64_t {aka long unsigned int}
src/cpu.c:148:77: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 5 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
  148 |     printf("mstatus=0x%016llx mtvec=0x%016llx mepc=0x%016llx mcause=0x%016llx\n",
      |                                                                       ~~~~~~^
      |                                                                             |
      |                                                                             long long unsigned int
      |                                                                       %016lx
......
  152 |         cpu_load_csr(cpu, MCAUSE));
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~                                            
      |         |
      |         uint64_t {aka long unsigned int}
src/cpu.c:153:29: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
  153 |     printf("sstatus=0x%016llx stvec=0x%016llx sepc=0x%016llx scause=0x%016llx\n",
      |                       ~~~~~~^
      |                             |
      |                             long long unsigned int
      |                       %016lx
  154 |         cpu_load_csr(cpu, SSTATUS),
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         |
      |         uint64_t {aka long unsigned int}
src/cpu.c:153:45: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
  153 |     printf("sstatus=0x%016llx stvec=0x%016llx sepc=0x%016llx scause=0x%016llx\n",
      |                                       ~~~~~~^
      |                                             |
      |                                             long long unsigned int
      |                                       %016lx
  154 |         cpu_load_csr(cpu, SSTATUS),
  155 |         cpu_load_csr(cpu, STVEC),
      |         ~~~~~~~~~~~~~~~~~~~~~~~~             
      |         |
      |         uint64_t {aka long unsigned int}
src/cpu.c:153:60: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
  153 |     printf("sstatus=0x%016llx stvec=0x%016llx sepc=0x%016llx scause=0x%016llx\n",
      |                                                      ~~~~~~^
      |                                                            |
      |                                                            long long unsigned int
      |                                                      %016lx
......
  156 |         cpu_load_csr(cpu, SEPC),
      |         ~~~~~~~~~~~~~~~~~~~~~~~                             
      |         |
      |         uint64_t {aka long unsigned int}
src/cpu.c:153:77: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 5 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
  153 |     printf("sstatus=0x%016llx stvec=0x%016llx sepc=0x%016llx scause=0x%016llx\n",
      |                                                                       ~~~~~~^
      |                                                                             |
      |                                                                             long long unsigned int
      |                                                                       %016lx
......
  157 |         cpu_load_csr(cpu, SCAUSE));
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~                                            
      |         |
      |         uint64_t {aka long unsigned int}
src/cpu.c: In function ‘cpu_dump_registers’:
src/cpu.c:606:36: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
  606 |         printf("x%-2d(%4s)=0x%016llx  ", i + 0, abi[i + 0], cpu->regs[i + 0]);
      |                              ~~~~~~^                        ~~~~~~~~~~~~~~~~
      |                                    |                                 |
      |                                    long long unsigned int            uint64_t {aka long unsigned int}
      |                              %016lx
src/cpu.c:607:36: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
  607 |         printf("x%-2d(%4s)=0x%016llx  ", i + 1, abi[i + 1], cpu->regs[i + 1]);
      |                              ~~~~~~^                        ~~~~~~~~~~~~~~~~
      |                                    |                                 |
      |                                    long long unsigned int            uint64_t {aka long unsigned int}
      |                              %016lx
src/cpu.c:608:36: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
  608 |         printf("x%-2d(%4s)=0x%016llx  ", i + 2, abi[i + 2], cpu->regs[i + 2]);
      |                              ~~~~~~^                        ~~~~~~~~~~~~~~~~
      |                                    |                                 |
      |                                    long long unsigned int            uint64_t {aka long unsigned int}
      |                              %016lx
src/cpu.c:609:36: error: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Werror=format=]
  609 |         printf("x%-2d(%4s)=0x%016llx\n", i + 3, abi[i + 3], cpu->regs[i + 3]);
      |                              ~~~~~~^                        ~~~~~~~~~~~~~~~~
      |                                    |                                 |
      |                                    long long unsigned int            uint64_t {aka long unsigned int}
      |                              %016lx
cc1: all warnings being treated as errors

**Comment by ksco** [comment]
Okay, I'll set up a Ubuntu environment later this week to confirm this issue.

**Comment by dzwduan** [comment]
bugs:
first type in ls，then cat README or echo hi
$ cat README
cat README
panic: sched locks

$ cat README
ccat README
panic: release

$ ehco hi
ehco hi
exec ehco failed

if ls not completed and get uart input,  get above errors

**Comment by ksco** [comment]
The clint device is not fully implemented, nanoemu never generate timer interrupts. But xv6 requires timer interrupts for process switching. Therefore, only the boot process is expected to work. If you are interested, you are welcome to implement the clint device and submit a PR. 😄

**Comment by ksco** [comment]
Hi @dzwduan, sorry for the late response, I've confirmed the compilation issue in Ubuntu you mentioned. I've summited a commit https://github.com/ksco/nanoemu/commit/41f86115d to fix this. I've set you up as a co-author, thanks!
